#!/usr/bin/env bash
# =============================================================================
# lock-dns.sh - stop the easy ways around the family resolver.
#
# Setting a filtering resolver only helps while the device keeps using it. An
# app (or a curious teenager) can point at 8.8.8.8, or a browser can send its
# queries over DNS-over-HTTPS to a resolver of its choice. This script installs
# an nftables table that:
#
#   * allows plain DNS (53) and DNS-over-TLS (853) only towards the approved
#     filtering resolvers, and drops every other DNS destination;
#   * optionally blocks the well-known public DoH endpoints on 443 (partial by
#     nature - pair it with the browser policies in configs/browser-policies/);
#   * on a router, transparently redirects LAN DNS queries to the filter.
#
#   sudo ./lock-dns.sh --provider cloudflare
#   sudo ./lock-dns.sh --mode router --lan-iface br0
#   sudo ./lock-dns.sh --revert
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=providers.sh
source "$SCRIPT_DIR/providers.sh"

PROVIDER="cloudflare"
MODE="host"
LAN_IFACE=""
REDIRECT_TO=""
BLOCK_DOH=0
REVERT=0
DRY_RUN=0
SAVE_PATH=""
TABLE="family_dns"

# Known DoH front-ends of unfiltered public resolvers. Not exhaustive - this is
# a speed bump, the browser policy files are the real fix.
# shellcheck disable=SC2034  # expanded inside the generated nftables ruleset
DOH_IPV4="1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 9.9.9.9 149.112.112.112 94.140.14.14 94.140.15.15 208.67.222.222 208.67.220.220 76.76.2.0 76.76.10.0 45.90.28.0 45.90.30.0"

usage() {
    cat <<USAGE
Usage: sudo $0 [options]

Options:
  -p, --provider NAME   Approved filtering resolver (default: cloudflare)
  -m, --mode MODE       host (this machine) | router (whole LAN)
  -l, --lan-iface IF    LAN interface, required for --mode router
      --redirect-to IP  DNAT target for --mode router (default: the provider's
                        primary IP; use the router's own IP when it runs Pi-hole)
      --block-doh       Also drop 443 towards well-known unfiltered DoH resolvers
      --save PATH       Write the ruleset to PATH (e.g. /etc/nftables.d/family-dns.nft)
  -r, --revert          Delete the nftables table again
  -n, --dry-run         Print the ruleset without applying it
  -h, --help            Show this help
USAGE
}

log()  { printf '[*] %s\n' "$*"; }
ok()   { printf '[+] %s\n' "$*"; }
die()  { printf '[x] %s\n' "$*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        -p|--provider)  PROVIDER="${2:?}"; shift 2 ;;
        -m|--mode)      MODE="${2:?}"; shift 2 ;;
        -l|--lan-iface) LAN_IFACE="${2:?}"; shift 2 ;;
        --redirect-to)  REDIRECT_TO="${2:?}"; shift 2 ;;
        --block-doh)    BLOCK_DOH=1; shift ;;
        --save)         SAVE_PATH="${2:?}"; shift 2 ;;
        -r|--revert)    REVERT=1; shift ;;
        -n|--dry-run)   DRY_RUN=1; shift ;;
        -h|--help)      usage; exit 0 ;;
        *) usage >&2; die "unknown option: $1" ;;
    esac
done

command -v nft >/dev/null 2>&1 || die "nftables (nft) is required"
[[ $DRY_RUN -eq 1 || $EUID -eq 0 ]] || die "run as root (sudo $0 ...)"

if [[ $REVERT -eq 1 ]]; then
    nft list table inet "$TABLE" >/dev/null 2>&1 && nft delete table inet "$TABLE" && ok "deleted table inet $TABLE"
    nft list table ip "${TABLE}_nat" >/dev/null 2>&1 && nft delete table ip "${TABLE}_nat" && ok "deleted table ip ${TABLE}_nat"
    exit 0
fi

provider_load "$PROVIDER" || die "unknown provider '$PROVIDER' (see --help)"
[[ "$MODE" == "router" && -z "$LAN_IFACE" ]] && die "--mode router needs --lan-iface"

allowed_v4="${P_IPV4// /, }"
allowed_v6="${P_IPV6// /, }"
primary_v4="${REDIRECT_TO:-${P_IPV4%% *}}"

build_ruleset() {
    cat <<NFT
# Generated by dns-family-filter/lock-dns.sh - provider: $P_NAME
table inet $TABLE {
    set approved_v4 {
        type ipv4_addr
        elements = { $allowed_v4 }
    }
$([[ -n "$allowed_v6" ]] && cat <<V6
    set approved_v6 {
        type ipv6_addr
        elements = { $allowed_v6 }
    }
V6
)
$([[ $BLOCK_DOH -eq 1 ]] && cat <<DOH
    set doh_bypass_v4 {
        type ipv4_addr
        elements = { ${DOH_IPV4// /, } }
    }
DOH
)
    chain output {
        type filter hook output priority filter; policy accept;

        # Local stub resolvers (systemd-resolved 127.0.0.53, dnsmasq, Pi-hole on
        # this host) must keep working - they forward to the approved resolver.
        oifname "lo" accept
        ip daddr 127.0.0.0/8 accept
        ip6 daddr ::1 accept

        # The approved filtering resolver is always reachable.
        ip daddr @approved_v4 udp dport 53 accept
        ip daddr @approved_v4 tcp dport { 53, 853 } accept
$([[ -n "$allowed_v6" ]] && cat <<V6
        ip6 daddr @approved_v6 udp dport 53 accept
        ip6 daddr @approved_v6 tcp dport { 53, 853 } accept
V6
)
$([[ $BLOCK_DOH -eq 1 ]] && cat <<DOH

        # Well-known unfiltered DoH front-ends.
        ip daddr @doh_bypass_v4 tcp dport 443 reject with tcp reset
        ip daddr @doh_bypass_v4 udp dport 443 drop
DOH
)
        # Everything else that speaks DNS is a bypass attempt.
        udp dport 53 drop
        tcp dport 53 reject with tcp reset
        tcp dport 853 reject with tcp reset
        udp dport 853 drop
    }
$([[ "$MODE" == "router" ]] && cat <<FWD

    chain forward {
        type filter hook forward priority filter; policy accept;

        ip daddr $primary_v4 udp dport 53 accept
        ip daddr @approved_v4 udp dport 53 accept
        ip daddr @approved_v4 tcp dport { 53, 853 } accept
        iifname "$LAN_IFACE" udp dport 53 drop
        iifname "$LAN_IFACE" tcp dport { 53, 853 } reject with tcp reset
    }
FWD
)
}
NFT

    if [[ "$MODE" == "router" ]]; then
        cat <<NAT

# Clients hard-coded to another resolver are transparently sent to the filter.
table ip ${TABLE}_nat {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
        iifname "$LAN_IFACE" ip daddr != $primary_v4 udp dport 53 dnat to $primary_v4
        iifname "$LAN_IFACE" ip daddr != $primary_v4 tcp dport 53 dnat to $primary_v4
    }
}
NAT
    fi
}

RULESET="$(build_ruleset)"

if [[ $DRY_RUN -eq 1 ]]; then
    printf '%s\n' "$RULESET"
    exit 0
fi

# Replace any previous version of our tables before loading the new one.
nft list table inet "$TABLE" >/dev/null 2>&1 && nft delete table inet "$TABLE"
nft list table ip "${TABLE}_nat" >/dev/null 2>&1 && nft delete table ip "${TABLE}_nat"

printf '%s\n' "$RULESET" | nft -f -
ok "nftables lock installed (mode: $MODE, provider: $P_NAME)"

if [[ -n "$SAVE_PATH" ]]; then
    mkdir -p "$(dirname "$SAVE_PATH")"
    printf '%s\n' "$RULESET" > "$SAVE_PATH"
    ok "ruleset saved to $SAVE_PATH (load at boot with: nft -f $SAVE_PATH)"
else
    log "rules are not persistent: re-run with --save /etc/nftables.d/family-dns.nft"
fi
log "undo with: sudo $0 --revert"
